// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLgNyaY4I4jMXfl0dOqoMUI8r6NHXjjY',
    appId: '1:854748341753:web:408593ab12ab629f1e4928',
    messagingSenderId: '854748341753',
    projectId: 'eydati-fcd79',
    authDomain: 'eydati-fcd79.firebaseapp.com',
    storageBucket: 'eydati-fcd79.firebasestorage.app',
    measurementId: 'G-K6P1NNB9NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA215z8nB6dSDswFErSnrS3fZGSjb2hJIY',
    appId: '1:854748341753:android:add22383848207e91e4928',
    messagingSenderId: '854748341753',
    projectId: 'eydati-fcd79',
    storageBucket: 'eydati-fcd79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHPjCSAcyHB3-DO97ctE1T0ag0lmPub4',
    appId: '1:854748341753:ios:4b9e044634a575711e4928',
    messagingSenderId: '854748341753',
    projectId: 'eydati-fcd79',
    storageBucket: 'eydati-fcd79.firebasestorage.app',
    iosBundleId: 'com.example.owner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHPjCSAcyHB3-DO97ctE1T0ag0lmPub4',
    appId: '1:854748341753:ios:4b9e044634a575711e4928',
    messagingSenderId: '854748341753',
    projectId: 'eydati-fcd79',
    storageBucket: 'eydati-fcd79.firebasestorage.app',
    iosBundleId: 'com.example.owner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLgNyaY4I4jMXfl0dOqoMUI8r6NHXjjY',
    appId: '1:854748341753:web:d8985acbc8eeb4611e4928',
    messagingSenderId: '854748341753',
    projectId: 'eydati-fcd79',
    authDomain: 'eydati-fcd79.firebaseapp.com',
    storageBucket: 'eydati-fcd79.firebasestorage.app',
    measurementId: 'G-E9FS6H9P12',
  );
}
